### ISSUE TITLE
Support React 18

### ISSUE THREAD

**Issue by tamas-kasa** [CharlesStover/react-segment-analytics#2]
Hello everyone 👋 ,

This module supports React 17 only but I'd like to use it with React 18.

I'm using npm 8 and I don't want to install deps with --legacy-peer-deps so it'd be great if you could let this module to be used with React 18. 

Thank you in advance.

**Comment by quisido** [comment]
Sure. This should be a pretty trivial change. 👍

**Comment by tamas-kasa** [comment]
@CharlesStover Thank you for your extremely fast response. You're the best 👍
