### ISSUE TITLE
Switch to @segment/analytics-next

### ISSUE THREAD

**Issue by tamas-kasa** [CharlesStover/react-segment-analytics#4]
Hey Charles 👋 

During npm install, there's this message: 
`@segment/analytics.js-core@4.1.11: Security updates will cease on August 31st, 2022. Please use @segment/analytics-next.`

Do you think you could switch to the aforementioned module? Your module is great and we would love to use it long term. 
Is there anything I can help you with regarding that?

**Comment by tamas-kasa** [comment]
I would probably solve the npm audit issues as well:

<img width="646" alt="Screenshot 2022-06-20 at 10 19 48" src="https://user-images.githubusercontent.com/104063616/174557565-12da55f2-ea08-4511-886a-e5b4ac281f35.png">

**Comment by quisido** [comment]
I'll have a look at if this is as simple as replacing one package with another, but given I am not on any projects that use Segment at the moment, I don't foresee this being high priority timeline-wise.

PRs are always welcome, but otherwise I'll try to make this change as time permits.

**Comment by quisido** [comment]
Releasing this now as a `2.0.0` major version bump.

Breaking changes:
1. Moved `@segment/analytics-next` from a `dependency` to a `peerDependency`, so you'll have to install it yourself alongside the `react-segment-analytics` module. This allows you to upgrade/patch the `@segment/analytics-next` module at will.
2. Removed `eventPrefix`. If you want event prefixes, I suggest using a custom hook:
```
import { useSegmentTrack } from 'react-segment-analytics';
function useTrack(eventName, ...args) {
  const track = useSegmentTrack();
  return track(`Prefix ${eventName}`, ...args);
}
```

**Comment by quisido** [comment]
I also added the Analytics browser settings and init options as props to the Segment component.
