### ISSUE TITLE
Any traits example (id, name, email)?

### ISSUE THREAD

**Issue by jfoliveira** [CharlesStover/react-segment-analytics#6]
Hi @CharlesStover,
Thanks for building and sharing this package publicly!

I could not find any examples on how to initialize the package using the identity traits.
- The README mentions [Be sure to provide the `id` trait](https://github.com/CharlesStover/react-segment-analytics/blob/main/README.md?plain=1#L48)
- Also I noticed one of your tests [ensure that identity is not called](https://github.com/CharlesStover/react-segment-analytics/blob/main/src/components/segment/segment.view.test.tsx#L35) when traits are not provided, but couldn't find no tests that check the correct usage of traits.

Could you provide an example on how to initialize it with id, name, email traits?

**Comment by jfoliveira** [comment]
I tried to consume `useIdentify` directly, but I'm not sure how it's supposed to be used, as the code below didn't work to be expecting me to provide another instance of `analytics`? 🤔 
```ts
  import useIdentify from 'react-segment-analytics'
  ...

  const identify = useIdentify()
  identify(user.id, { email: user.email, name: user.name })
```

```
(alias) useIdentify({ AnalyticsBrowser, children, traits, ...rest }: 
Readonly<Props>): React.ReactElement<any, string | React.JSXElementConstructor<any>>

import useIdentify

Expected 1 arguments, but got 0.ts(2554)
segment.view.d.ts(10, 33): An argument matching this binding pattern was not provided.
```

Any help would be appreciated on the simplest way to identify user/traits using this component.
Thanks!

**Comment by quisido** [comment]
`useIdentify` is not meant to be called by the consumer. You would pass a `traits` prop to the `<Segment>` component, like so:

```
<Segment traits={{ id: 'my-unique-id' }}>
  <MyApp />
</Segment>
```

Let me know if you have any other questions.
